rootProject.name = "trip"

include("common")
include("user-service")
include("trip-service")
include("booking-service")
include("payment-service")
include("eureka-server")
include("api-gateway")
include("proto")
include("accommodation-service")
include("subscription-service")
include("feed-service")
include("media-service")
include("chat-service")
include("notification-service")
