server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: oauth2-service
          uri: lb://user-service
          predicates:
            - Path=/oauth2/**, /login/oauth2/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trips/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

jwt:
  secret: dHJpcC1zZXJ2aWNlLWp3dC1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1lbm91Z2gtZm9yLWhtYWMtc2hhMjU2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
