server:
  port: 8086

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://localhost:3000/trip_subscription?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: subscription-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

internal:
  auth:
    secret: dHJpcC1pbnRlcm5hbC1zZXJ2aWNlLWF1dGgtc2VjcmV0LWtleQ==

portone:
  api-secret: ${PORTONE_API_SECRET:test-secret}
  store-id: ${PORTONE_STORE_ID:test-store}

grpc:
  server:
    port: 9086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
